---

project_structure:
  build: build
  contracts: contracts
  reports: reports
  scripts: cmd
  tests: tests

networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings: null

compiler:
  evm_version: null
  vyper:
    version: null

console:
  show_colors: false

hypothesis:
  deadline: null
  max_examples: 50
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

autofetch_sources: false
dependencies: null
dev_deployment_artifacts: false
